name: pull_request

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3

    - name: deps
      run: lein deps

    - name: lint
      run: lein clj-kondo --lint src test

    - name: cljfmt
      run: lein cljfmt check

    - name: test
      run: lein test
